/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/scene.glb 
*/

import React from 'react'
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei'
import { useEffect } from 'react'
import * as THREE from 'three'
import {motion} from 'framer-motion-3d'
 
export function Office(props) {
  const { nodes, materials } = useGLTF('models/scene.glb')
  const texture = useVideoTexture("textures/s.mp4");
  texture.flipY = false

  const {section} = props

  const addShadowProps = (meshProps = {}) => ({
    ...meshProps,
    castShadow: true,
    receiveShadow: true,
  })

  // Make materials less shiny for more natural look
  React.useEffect(() => {
    Object.values(materials).forEach(material => {
      material.roughness = 0.8
      material.metalness = 0.2
    })
  }, [materials])
  
  return (
    <group {...props} dispose={null} >

<mesh name="Screen" geometry={nodes.Screen.geometry} material={materials.screen} position={[-5.164, 7.164, -7.583]} rotation={[2.345, 1.561, -2.346]} scale={0.773} >
<meshBasicMaterial map={texture} toneMapped={false}  />
</mesh>

<motion.mesh 
scale={[0,0,0]}
animate={{
  scale:section === 0 ? 0.773 : 0,
}}
name="Computer" geometry={nodes.Computer.geometry} material={materials.PC} 
position={[-5.164, 7.164, -7.583]} rotation={[2.345, 1.561, -2.346]}  />

      <motion.mesh
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
        rotateY: section === 0 ? Math.PI * 2.2 : Math.PI / 4
      }}
       {...addShadowProps()} name="Chair" geometry={nodes.Chair.geometry} material={materials['Table Top']} position={[-6.361, 3.69, -0.918]} rotation={[0.004, 0.63, -0.008]} 
      //  scale={0.773} 
       />

      <group name="Body" position={[4.812, 8.872, -8.949]} rotation={[2.345, 1.561, 2.366]} scale={[0.661, 0.773, 0.773]}>
        <mesh {...addShadowProps()} name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Wall 2']} />
        <mesh {...addShadowProps()} name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.Wall} />
        <mesh {...addShadowProps()} name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials['Drawer-out']} />
      </group>

      <motion.group
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
      name="Trash002" position={[-7.786, -0.16, -6.964]} rotation={[3.132, 0.821, -3.135]} 
      // scale={0.773}
      >
        <mesh {...addShadowProps()} name="Cube137" geometry={nodes.Cube137.geometry} material={materials['Trash Lid']} />
        <mesh {...addShadowProps()} name="Cube137_1" geometry={nodes.Cube137_1.geometry} material={materials.Material} />
      </motion.group>

      <group name="Table_Top001" position={[-2.365, 2.45, -6.476]} rotation={[-0.001, 0.004, -0.007]} scale={0.773}>
        <mesh {...addShadowProps()} name="Cube153" geometry={nodes.Cube153.geometry} material={materials['Drawer out.005']} />
        <mesh {...addShadowProps()} name="Cube153_1" geometry={nodes.Cube153_1.geometry} material={materials['Table Top.004']} />
        <mesh {...addShadowProps()} name="Cube153_2" geometry={nodes.Cube153_2.geometry} material={materials['Top.004']} />
      </group>

      <motion.mesh 
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
      {...addShadowProps()} name="ChairStand" geometry={nodes.ChairStand.geometry} material={materials.Box} position={[-6.063, 0.853, -0.849]} rotation={[3.132, 0.821, -3.135]} 
      // scale={0.773} 
      />

      <motion.mesh
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
       {...addShadowProps()} name="Wheel3" geometry={nodes.Wheel3.geometry} material={materials.Sand} position={[-5.434, 0.8, -0.098]} rotation={[-0.001, 0.708, -0.006]} 
      //  scale={0.773}
        />

      <motion.mesh 
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
      {...addShadowProps()} name="Shelves" geometry={nodes.Shelves.geometry} material={materials['Table Top']} position={[7.561, 6.943, 2.777]} rotation={[-0.612, 1.569, 0.605]} 
      // scale={0.773} 
      />

      <motion.group
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
       name="box" position={[6.553, 7.303, 4.746]} rotation={[-2.955, -1.566, -2.962]} 
      //  scale={0.773}
       >
        <mesh {...addShadowProps()} name="Cube075" geometry={nodes.Cube075.geometry} material={materials.screen} />
        <mesh {...addShadowProps()} name="Cube075_1" geometry={nodes.Cube075_1.geometry} material={materials['Drawer-out']} />
        <mesh {...addShadowProps()} name="Cube075_2" geometry={nodes.Cube075_2.geometry} material={materials.Box} />
      </motion.group>

      <motion.group 
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
      name="show" position={[6.908, 8.071, -0.839]} rotation={[-2.433, 0.634, 1.798]} 
      // scale={0.773}
      >
        <mesh {...addShadowProps()} name="Cube100" geometry={nodes.Cube100.geometry} material={materials.Leaves} />
        <mesh {...addShadowProps()} name="Cube100_1" geometry={nodes.Cube100_1.geometry} material={materials.TrackPad} />
      </motion.group>

      <motion.group
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
       name="books1" position={[7.055, 11.181, -1.603]} rotation={[0.299, -1.568, 0.306]} 
      //  scale={0.773}
       >
        <mesh {...addShadowProps()} name="Cube148" geometry={nodes.Cube148.geometry} material={materials['Drawer-out']} />
        <mesh {...addShadowProps()} name="Cube148_1" geometry={nodes.Cube148_1.geometry} material={materials['Trash Lid']} />
        <mesh {...addShadowProps()} name="Cube148_2" geometry={nodes.Cube148_2.geometry} material={materials.Sand} />
      </motion.group>

      <motion.group 
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
      name="books2" position={[7.177, 11.826, 5.936]} rotation={[-1.889, 0.005, -3.133]} 
      // scale={0.773}
      >
        <mesh {...addShadowProps()} name="Cube154" geometry={nodes.Cube154.geometry} material={materials['screen.008']} />
        <mesh {...addShadowProps()} name="Cube154_1" geometry={nodes.Cube154_1.geometry} material={materials['Drawer-out']} />
        <mesh {...addShadowProps()} name="Cube154_2" geometry={nodes.Cube154_2.geometry} material={materials.PC} />
        <mesh {...addShadowProps()} name="Cube154_3" geometry={nodes.Cube154_3.geometry} material={materials.Leaves} />
        <mesh {...addShadowProps()} name="Cube154_4" geometry={nodes.Cube154_4.geometry} material={materials.Box} />
      </motion.group>

      <motion.mesh 
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
      {...addShadowProps()} name="CirTable" geometry={nodes.CirTable.geometry} material={materials['Table Top']} position={[4.754, 5.236, -6.132]} rotation={[3.132, 0.821, -3.135]} 
      // scale={[0.773, 0.784, 0.773]} 
      />

      <group name="Table" position={[-9.667, 0.249, -6.603]} rotation={[-0.001, 0.01, -0.007]} scale={[0.773, 0.777, 0.773]}>
        <mesh {...addShadowProps()} name="Cube257" geometry={nodes.Cube257.geometry} material={materials['Table Leg']} />
        <mesh {...addShadowProps()} name="Cube257_1" geometry={nodes.Cube257_1.geometry} material={materials['Table Top']} />
        <mesh {...addShadowProps()} name="Cube257_2" geometry={nodes.Cube257_2.geometry} material={materials['Table Leg Black']} />
      </group>

      <motion.group 
      scale={[0,0,0]}
      animate={{
        scale:section === 0 ? 0.773 : 0,
      }}
      name="CPU" position={[-9.608, 5.906, -7.564]} rotation={[1.978, 1.563, -1.979]}
      //  scale={0.773}
       >
        <mesh {...addShadowProps()} name="Cube311" geometry={nodes.Cube311.geometry} material={materials.Key} />
        <mesh {...addShadowProps()} name="Cube311_1" geometry={nodes.Cube311_1.geometry} material={materials['Trash Lid']} />
      </motion.group>

      <group name="MoushTrack" position={[-9.345, 5.139, -3.473]} rotation={[0.111, 0.004, -0.007]} scale={0.773}>
        <mesh {...addShadowProps()} name="Cube314" geometry={nodes.Cube314.geometry} material={materials.TrackPad} />
        <mesh {...addShadowProps()} name="Cube314_1" geometry={nodes.Cube314_1.geometry} material={materials['Table Leg']} />
      </group>

      <mesh {...addShadowProps()} name="Table_Top2" geometry={nodes.Table_Top2.geometry} material={materials['Table Top']} position={[-4.916, 6.033, -7.634]} rotation={[-0.001, -0.002, -0.007]} scale={0.773} />

      <mesh {...addShadowProps()} name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-0.513, 6.348, -5.551]} rotation={[0.031, 1.352, -0.031]} scale={0.773} />

      <group name="Circle" position={[0.856, 6.152, -7.274]} rotation={[0.001, -0.02, -0.007]} scale={0.773}>
        <mesh {...addShadowProps()} name="Circle043" geometry={nodes.Circle043.geometry} material={materials.Leaves} />
        <mesh {...addShadowProps()} name="Circle043_1" geometry={nodes.Circle043_1.geometry} material={materials.Sand} />
      </group>

      <group name="keyboard" position={[-4.513, 5.288, -5.249]} rotation={[2.712, 1.555, -2.677]} scale={0.773}>
        <mesh {...addShadowProps()} name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Key.001']} />
        <mesh {...addShadowProps()} name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials['Drawer out.001']} />
      </group>

    </group>

  )
}

useGLTF.preload('models/scene.glb')
useTexture.preload("textures/s.mp4");
